language: node_js

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  directories:
    - ~/.npm
    - node_modules

node_js:
- node

install:
  - npm ci

script:
  - npm test
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release